version: '3.9'

services:

  #-------------------
  # Mongo DB service -
  #-------------------
  mongo:
    image: mongo:${MONGO_VERSION}
    hostname: mongo-lab
    container_name: mongo
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo-db:/data/db/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    networks:
      - dev-network

  #------------------------
  # Mongo express service -
  #------------------------
  mongo-express:
    container_name: mongo-express:${MONGO_EXPRESS_VERSION}
    image:  mongo-express
    hostname: mongo-lab
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - dev-network

#-------------------
# External network -
#-------------------
networks:
  dev-network:
    driver: bridge
    external: true

#-------------------
# External volumes -
#-------------------
volumes:
  mongo-db:
    external: true